name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_gpu:
    sdk: flutter
    
  gpu_vector_tile_renderer:
    path: ..

  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Ffi / Native assets
  ffi: ^2.1.3
  flutter_gpu_shaders: ^0.1.3
  native_assets_cli: ^0.8.0
  native_toolchain_c: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - build/shaderbundles/
